name: Pipeline

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        env: 
            DATABASE_URL: ${{secrets.DATABASE_URL}}
            SECRET_KEY: ${{secrets.SECRET_KEY}}
            ALGORITHM: ${{secrets.ALGORITHM}}
            ACCESS_TOKEN_EXPIRES_IN_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRES_IN_MINUTES}}
        steps:
            - name: copia arquivos
              uses: actions/checkout@v3

            - name: instalar python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            
            - name: instalar poetry
              run: pip install poetry

            - name: instalar dependências
              run: poetry install

            - name: executar testes
              run: poetry run task test

            - name: gerar coverage.xml
              run: poetry run task

            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

